Update script and README.

diff --git a/escape-go b/escape-go
--- a/escape-go
+++ b/escape-go
@@ -16,7 +16,14 @@ Pattern=$(echo "$Hatches" | cut -d: -f-2 | tr : ' ' |
 "$Check" -algo=pta -test . |
 cut -d: -f-2 | tr '\n' '|' | sed 's/.$//')
 
-echo "$Hatches" | grep -E "$Pattern" |
+Errors=$(echo "$Hatches" | grep -E "$Pattern" |
 sed -e 's/.* generated by escape: //g' |
 sed -re 's/[^:]+$/ problem with escape()/g' |
-sed -e "s|${Working}/||g"
+sed -e "s|${Working}/||g")
+
+if [ -n "$Errors" ]; then
+	echo "$Errors" >&2
+	exit 1
+fi
+
+exit 0
