Add examples of use.

diff --git a/expand-escape b/expand-escape
--- a/expand-escape
+++ b/expand-escape
@@ -1,9 +1,7 @@
 #!/bin/sh
 
 # Defaults.
-: ${Check:=check} ${Escape:=escape}
-
-Working=$(pwd)
+: ${Check:=check} ${Escape:=escape} ${Working:=$(pwd)}
 
 Hatches=$(find "$Working" -name '*.ego' |
 while read Path; do
@@ -13,17 +11,19 @@ while read Path; do
 done)
 
 Pattern=$(echo "$Hatches" | cut -d: -f-2 | tr : ' ' |
-"$Check" -test . |
+"$Check" -algo=pta -test . |
 cut -d: -f-2 | tr '\n' '|' | sed 's/.$//')
 
-Errors=$(echo "$Hatches" | grep -E "$Pattern" |
-sed -e 's/.* generated by escape: //g' |
-sed -re 's/[^:]+$/ problem with escape()/g' |
-sed -e "s|${Working}/||g")
+if [ -n "$Pattern" ]; then
+	Errors=$(echo "$Hatches" | grep -E "$Pattern" |
+	sed -e 's/.* generated by escape: //g' |
+	sed -re 's/[^:]+$/ problem with escape()/g' |
+	sed -e "s|${Working}/||g")
 
-if [ -n "$Errors" ]; then
-	echo "$Errors" >&2
-	exit 1
+	if [ -n "$Errors" ]; then
+		echo "$Errors" >&2
+		exit 1
+	fi
 fi
 
 exit 0
